<html>
    <body></body>
</html>

<script>
// Callbacks with error handling
function loadScript(src, callback) {
  var script = document.createElement("script");
  script.src = src;
  script.onload = function() {
    console.log("Loaded script with SRC: " + src)
    callback(null, src);
  }
  script.onerror = function() {
    console.warn("Error loading script with SRC: " + src);
    callback(new Error("Src got some error"))
  }
  document.body.appendChild(script);
}

function hello(error, src) {
  if (error) {
    console.warn(error) //error if script not loaded
    return
  }
  console.log('Hello World! ' + src);
}

loadScript("https://cdn.jsdlivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js", hello) //src with wrong url //will genreate error

loadScript("https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js", hello) 

//callback problems -
//pyramid of doom or callback hell - inside callback function calling nested callbacks
//error handling will be hard

//----- promises
//solution to callback hell problem
const loadScriptPromise = (src) => {
    return new Promise((resolve, reject) => {
        let script = document.createElement("script")
        script.type = "text/javascript"
        script.src = src
        document.body.appendChild(script)
        script.onload = (script) => {
            resolve("Script has been loaded")
        }
        script.onerror = () => { reject(0) }
    })
}

let p1 = loadScriptPromise("https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js")
p1.then((value) => {
        console.log(value)
        return loadScriptPromise("https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js")
}).then((value) => {
        console.log("Second script ready")
}).catch((error) => {
        console.log("We are sorry but we are having problems loading this script")
})
</script>